import os
import json
from dotenv import load_dotenv

def sync_env_to_config():
    """
    Reads public variables from .env and writes them to a config.js 
    file that the browser can safely load.
    """
    load_dotenv()
    
    # We only export safe, public-facing variables.
    # NEVER export SUPABASE_KEY (service role) or AI API Keys.
    config = {
        "SUPABASE_URL": os.environ.get("SUPABASE_URL", ""),
        "SUPABASE_ANON_KEY": os.environ.get("SUPABASE_ANON_KEY", "")
    }
    
    config_path = "config.js"
    try:
        with open(config_path, "w") as f:
            f.write("// This file is auto-generated by sync_config.py\n")
            f.write(f"window.CONFIG = {json.dumps(config, indent=2)};")
        print(f"[Sync] Successfully generated {config_path}")
        return True
    except Exception as e:
        print(f"[Sync] Error writing config.js: {e}")
        return False

if __name__ == "__main__":
    sync_env_to_config()
