import os
import json
import argparse
import sqlite3
from dotenv import load_dotenv

def sync_env_to_config(env="production"):
    """
    Reads variables from .env and writes them to a config.js 
    file that the browser can safely load. Supports multiple environments.
    """
    load_dotenv()
    env = env.lower()
    
    url = ""
    key = ""
    local_data = []
    
    if env == "staging":
        url = os.environ.get("STAGING_SUPABASE_URL", "")
        key = os.environ.get("STAGING_SUPABASE_ANON_KEY", "")
        print(f"[Sync] Using STAGING credentials.")
    elif env == "local":
        print(f"[Sync] Extracting data from local SQLite database...")
        db_path = "ai_radio_dev.db"
        if os.path.exists(db_path):
            try:
                conn = sqlite3.connect(db_path)
                conn.row_factory = sqlite3.Row
                c = conn.cursor()
                c.execute("SELECT * FROM memory_log ORDER BY created_at DESC")
                rows = c.fetchall()
                for r in rows:
                    d = dict(r)
                    # Convert stringified lists back to real lists for JS
                    try: d["topic_tags"] = json.loads(d["topic_tags"]) if d["topic_tags"] else []
                    except: pass
                    try: d["related_ids"] = json.loads(d["related_ids"]) if d["related_ids"] else []
                    except: pass
                    local_data.append(d)
                conn.close()
                print(f"[Sync] Exported {len(local_data)} episodes to config.js")
            except Exception as e:
                print(f"[Sync] Error reading SQLite: {e}")
        else:
            print(f"[Sync] WARNING: ai_radio_dev.db not found. Dashboard will be empty.")
    else:
        url = os.environ.get("SUPABASE_URL", "")
        key = os.environ.get("SUPABASE_ANON_KEY", "")
        print(f"[Sync] Using PRODUCTION credentials.")

    config = {
        "SUPABASE_URL": url,
        "SUPABASE_ANON_KEY": key,
        "APP_ENV": env,
        "LOCAL_DATA": local_data
    }
    
    config_path = "config.js"
    try:
        with open(config_path, "w") as f:
            f.write(f"// Auto-generated by sync_config.py for {env.upper()}\n")
            f.write(f"window.CONFIG = {json.dumps(config, indent=2)};")
        print(f"[Sync] Successfully generated {config_path}")
        return True
    except Exception as e:
        print(f"[Sync] Error writing config.js: {e}")
        return False

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Sync .env to frontend config.js")
    parser.add_argument("--env", choices=["production", "staging", "local"], default="production", help="The environment to sync.")
    args = parser.parse_args()
    sync_env_to_config(env=args.env)
