"""
sync_config.py — Writes config.js for the AI Radio Echo HTML dashboard.

For local database envs (local, prod-models):
  Reads the 20 most recent episodes from SQLite and exports them to config.js
  as a JS-compatible const so the dashboard can render them without a server.

For production database envs (prod-db, production):
  Writes Supabase credentials to config.js so the dashboard queries live data
  directly from the browser.

config.js is in .gitignore and must never be committed.
"""

import json
import os

SQLITE_ENVS   = {"local", "prod-models"}
SUPABASE_ENVS = {"prod-db", "production"}
CONFIG_PATH   = "config.js"


def sync_env_to_config(env: str, db=None):
    """
    Generate config.js appropriate for the active environment.

    Args:
        env: Active environment string.
        db:  An initialised DBClient instance (required for local DB envs).
             Ignored for Supabase envs.
    """
    if env in SQLITE_ENVS:
        _write_sqlite_config(db)
    elif env in SUPABASE_ENVS:
        _write_supabase_config()
    else:
        print(f"[SyncConfig] Unknown env '{env}'. config.js not written.")


# ---------------------------------------------------------------------------
# Backends
# ---------------------------------------------------------------------------

def _write_sqlite_config(db):
    """
    Read the 20 most recent episodes from SQLite and write them to config.js.
    The dashboard reads this file as a static JS module.
    """
    if db is None:
        print("[SyncConfig] No DBClient provided for SQLite config sync. Skipping.")
        return

    try:
        episodes = db.fetch_recent_memory(20)
    except Exception as exc:
        print(f"[SyncConfig] Failed to read episodes from SQLite: {exc}")
        episodes = []

    config_obj = {
        "source":   "sqlite",
        "episodes": episodes,
    }

    content = (
        "// Auto-generated by sync_config.py — do not edit manually.\n"
        "// This file is in .gitignore and is never committed.\n"
        f"const CONFIG = {json.dumps(config_obj, indent=2, default=str)};\n"
    )

    try:
        with open(CONFIG_PATH, "w", encoding="utf-8") as fh:
            fh.write(content)
        print(f"[SyncConfig] config.js written ({len(episodes)} episodes from SQLite).")
    except Exception as exc:
        print(f"[SyncConfig] Failed to write config.js: {exc}")


def _write_supabase_config():
    """
    Write Supabase credentials to config.js so the dashboard can query live data.
    The WEBSITE_URL env var is also included for metadata display.
    """
    supabase_url = os.environ.get("SUPABASE_URL", "").strip()
    supabase_key = os.environ.get("SUPABASE_KEY", "").strip()
    website_url  = os.environ.get("WEBSITE_URL", "").strip()

    if not supabase_url or not supabase_key:
        print(
            "[SyncConfig] Warning: SUPABASE_URL or SUPABASE_KEY not set. "
            "config.js will be written with empty credentials."
        )

    config_obj = {
        "source":       "supabase",
        "supabase_url": supabase_url,
        "supabase_key": supabase_key,
        "website_url":  website_url,
    }

    content = (
        "// Auto-generated by sync_config.py — do not edit manually.\n"
        "// This file is in .gitignore and is never committed.\n"
        f"const CONFIG = {json.dumps(config_obj, indent=2)};\n"
    )

    try:
        with open(CONFIG_PATH, "w", encoding="utf-8") as fh:
            fh.write(content)
        print("[SyncConfig] config.js written with Supabase credentials.")
    except Exception as exc:
        print(f"[SyncConfig] Failed to write config.js: {exc}")
